name: Docker Image CI

on:
  push:
    branches: [ "latest" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    environment: ${( github.ref_name )}
    
    steps:
    
    - name: Checkput
      uses: actions/checkout@v3

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0
      
    - name: Docker Login
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_ACCESS_TOKEN }}

    - name: Docker Metadata action
      uses: docker/metadata-action@v5.0.0
      with:
        images: ${{ vars.IMAGE_NAME }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        build-args: ALPINE_TAG=${{ vars.ALPINE_TAG }}
        context: .
        labels: ${{ steps.eta.outputs.labels }}
        platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ vars.IMAGE_NAME }}:${{ vars.ALPINE_TAG }}
