name: Docker Image CI

on:
  push:
    branches: [ "3.15.10", "3.16.7", "3.17.5", "3.18.4", "latest" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    environment: ${{ github.ref_name }}
    
    steps:
    
    - name: Checkput
      uses: actions/checkout@v3

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0
      
    - name: Docker Login
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_ACCESS_TOKEN }}

    - name: Docker Metadata action
      uses: docker/metadata-action@v5.0.0
      with:
        images: ${{ vars.IMAGE_NAME }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        build-args: ALPINE_TAG=${{ vars.ALPINE_TAG }}
        context: .
        file: ./Dockerfile
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ vars.IMAGE_NAME }}:${{ vars.ALPINE_TAG }}

    - name: Docker Hub Description
      if: github.ref_name == 'latest'
      uses: peter-evans/dockerhub-description@v3.4.2
      with:
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_ACCESS_TOKEN }}
        repository: ${{ vars.IMAGE_NAME }}
        short-description: Docker Image - Alpine-based image with cURL
        readme-filepath: ./README.md
